services:
  mariadb:
    image: mariadb:latest
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql

  redis-cache:
    image: redis:alpine
    restart: always

  redis-queue:
    image: redis:alpine
    restart: always

  configurator:
    image: frappe/bench:latest
    entrypoint:
      - bash
      - -c
    command: >
      if [ ! -f /home/frappe/frappe-bench/.configured ]; then
        sudo chown -R frappe:frappe /home/frappe/frappe-bench && 
        bench init --skip-redis-config-generation --version=${FRAPPE_VERSION} --ignore-exist /home/frappe/frappe-bench-tmp && 
        cd frappe-bench && 
        bench set-config -g db_type mariadb && 
        bench set-config -g db_host mariadb && 
        bench set-config -g redis_cache redis://redis-cache:6379 && 
        bench set-config -g redis_queue redis://redis-queue:6379 && 
        bench set-config -g redis_socketio redis://redis-queue:6379 && 
        bench set-config -gp developer_mode 1 && 
        bench new-site -no-mariadb-socket --db-root-password=${DB_ROOT_PASSWORD} --admin-password=${SITE_PASSWORD} --set-default ${SITE_NAME} && 
        bench enable-scheduler && 
        cp -rf /home/frappe/frappe-bench-tmp/* /home/frappe/frappe-bench/ && 
        rm -rf /home/frappe/frappe-bench-tmp/ &&
        touch /home/frappe/frappe-bench/.configured
      else
        echo "Configuration already completed."
      fi
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
    volumes:
      - frappe-data:/home/frappe/frappe-bench
    working_dir: /home/frappe

  web:
    image: frappe/bench:latest
    command: >
      /home/frappe/frappe-bench/env/bin/gunicorn -b 0.0.0.0:8000 -w 4 --max-requests 1200 --max-requests-jitter 50 -t 120 frappe.app:application --preload
    ports:
      - "8000:8000"
    volumes:
      - frappe-data:/home/frappe/frappe-bench
    working_dir: /home/frappe/frappe-bench
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
    restart: always

  socketio:
    image: frappe/bench:latest
    command: node apps/frappe/socketio.js
    ports:
      - "9000:9000"
    volumes:
      - frappe-data:/home/frappe/frappe-bench
    working_dir: /home/frappe/frappe-bench
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
    restart: always

  watch:
    image: frappe/bench:latest
    command: bench watch
    volumes:
      - frappe-data:/home/frappe/frappe-bench
    working_dir: /home/frappe/frappe-bench
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
    restart: always

  schedule:
    image: frappe/bench:latest
    command: bench schedule
    volumes:
      - frappe-data:/home/frappe/frappe-bench
    working_dir: /home/frappe/frappe-bench
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
    restart: always

  worker_short:
    image: frappe/bench:latest
    command: bench worker --queue short
    volumes:
      - frappe-data:/home/frappe/frappe-bench
    working_dir: /home/frappe/frappe-bench
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
    restart: always

  worker_long:
    image: frappe/bench:latest
    command: bench worker --queue long
    volumes:
      - frappe-data:/home/frappe/frappe-bench
    working_dir: /home/frappe/frappe-bench
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
    restart: always

  worker_default:
    image: frappe/bench:latest
    volumes:
      - frappe-data:/home/frappe/frappe-bench
    working_dir: /home/frappe/frappe-bench
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
    restart: always

volumes:
  mariadb-data:
  frappe-data:
