services:
  mariadb:
    image: mariadb:latest
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql

  redis-cache:
    image: redis:alpine
    restart: always

  redis-queue:
    image: redis:alpine
    restart: always

  configurator:
    image: frappe/bench:latest
    entrypoint:
      - bash
      - -c
    command:
      - >
        if [ ! -f /home/frappe/frappe-bench/.configured ]; then
          sudo chown -R frappe:frappe /home/frappe/frappe-bench &&
          sudo chown -R frappe:frappe /home/frappe/logs &&
          bench init --skip-redis-config-generation --version=${FRAPPE_VERSION} --ignore-exist frappe-bench &&
          cd frappe-bench &&
          bench set-config -g db_type mariadb &&
          bench set-config -g db_host mariadb &&
          bench set-config -g redis_cache redis://redis-cache:6379 &&
          bench set-config -g redis_queue redis://redis-queue:6379 &&
          bench set-config -g redis_socketio redis://redis-queue:6379 &&
          bench set-config -gp developer_mode 1 &&
          bench new-site --no-mariadb-socket --db-root-password=${DB_ROOT_PASSWORD} --admin-password=${SITE_PASSWORD} --set-default ${SITE_NAME} &&
          bench enable-scheduler &&
          pip install --no-warn-script-location -U -e ./apps/frappe &&
          touch /home/frappe/frappe-bench/.configured
        else
          echo "Configuration already completed."
        fi
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
    volumes:
      - frappe-data:/home/frappe/frappe-bench
      - frappe-sites:/home/frappe/frappe-bench/sites
      - frappe-logs:/home/frappe/logs
    working_dir: /home/frappe

  gunicorn:
    image: frappe/bench:latest
    entrypoint:
      - bash
      - -c
    command:
      - >
        while [ ! -f /home/frappe/frappe-bench/.configured ]; do
          echo "Waiting for configuration to complete...";
          sleep 60;
        done;
        echo "Configuration detected, starting service...";
        /home/frappe/frappe-bench/env/bin/gunicorn -b 0.0.0.0:8000 -w 4 --max-requests 1200 --max-requests-jitter 50 -t 120 frappe.app:application --preload
    ports:
      - "8000:8000"
    volumes:
      - frappe-data:/home/frappe/frappe-bench
      - frappe-sites:/home/frappe/frappe-bench/sites
      - frappe-logs:/home/frappe/logs
    working_dir: /home/frappe/frappe-bench
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
    restart: always

  socketio:
    image: frappe/bench:latest
    entrypoint:
      - bash
      - -c
    command:
      - >
        while [ ! -f /home/frappe/frappe-bench/.configured ]; do
          echo "Waiting for configuration to complete...";
          sleep 60;
        done;
        echo "Configuration detected, starting service...";
        node apps/frappe/socketio.js
    ports:
      - "9000:9000"
    volumes:
      - frappe-data:/home/frappe/frappe-bench
      - frappe-sites:/home/frappe/frappe-bench/sites
      - frappe-logs:/home/frappe/logs
    working_dir: /home/frappe/frappe-bench
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
    restart: always

  watch:
    image: frappe/bench:latest
    entrypoint:
      - bash
      - -c
    command:
      - >
        while [ ! -f /home/frappe/frappe-bench/.configured ]; do
          echo "Waiting for configuration to complete...";
          sleep 60;
        done;
        echo "Configuration detected, starting service...";
        bench watch
    volumes:
      - frappe-data:/home/frappe/frappe-bench
      - frappe-sites:/home/frappe/frappe-bench/sites
      - frappe-logs:/home/frappe/logs
    working_dir: /home/frappe/frappe-bench
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
    restart: always

  schedule:
    image: frappe/bench:latest
    entrypoint:
      - bash
      - -c
    command:
      - >
        while [ ! -f /home/frappe/frappe-bench/.configured ]; do
          echo "Waiting for configuration to complete...";
          sleep 60;
        done;
        echo "Configuration detected, starting service...";
        bench schedule
    volumes:
      - frappe-data:/home/frappe/frappe-bench
      - frappe-sites:/home/frappe/frappe-bench/sites
      - frappe-logs:/home/frappe/logs
    working_dir: /home/frappe/frappe-bench
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
    restart: always

  worker_short:
    image: frappe/bench:latest
    entrypoint:
      - bash
      - -c
    command:
      - >
        while [ ! -f /home/frappe/frappe-bench/.configured ]; do
          echo "Waiting for configuration to complete...";
          sleep 60;
        done;
        echo "Configuration detected, starting service...";
        bench worker --queue short
    volumes:
      - frappe-data:/home/frappe/frappe-bench
      - frappe-sites:/home/frappe/frappe-bench/sites
      - frappe-logs:/home/frappe/logs
    working_dir: /home/frappe/frappe-bench
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
    restart: always

  worker_long:
    image: frappe/bench:latest
    entrypoint:
      - bash
      - -c
    command:
      - >
        while [ ! -f /home/frappe/frappe-bench/.configured ]; do
          echo "Waiting for configuration to complete...";
          sleep 60;
        done;
        echo "Configuration detected, starting service...";
        bench worker --queue long
    volumes:
      - frappe-data:/home/frappe/frappe-bench
      - frappe-sites:/home/frappe/frappe-bench/sites
      - frappe-logs:/home/frappe/logs
    working_dir: /home/frappe/frappe-bench
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
    restart: always

  worker_default:
    image: frappe/bench:latest
    entrypoint:
      - bash
      - -c
    command:
      - >
        while [ ! -f /home/frappe/frappe-bench/.configured ]; do
          echo "Waiting for configuration to complete...";
          sleep 60;
        done;
        echo "Configuration detected, starting service...";
        bench worker --queue default
    volumes:
      - frappe-data:/home/frappe/frappe-bench
      - frappe-sites:/home/frappe/frappe-bench/sites
      - frappe-logs:/home/frappe/logs
    working_dir: /home/frappe/frappe-bench
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
    restart: always

  web:
    image: frappe/erpnext:latest
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: gunicorn:8000
      SOCKETIO: socketio:9000
      FRAPPE_SITE_NAME_HEADER: ${SITE_NAME:-$$host}
      UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
      UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
      UPSTREAM_REAL_IP_RECURSIVE: ${UPSTREAM_REAL_IP_RECURSIVE:-off}
      PROXY_READ_TIMEOUT: ${PROXY_READ_TIMEOUT:-120}
      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE:-50m}
    volumes:
      - frappe-sites:/home/frappe/frappe-bench/sites
    depends_on:
      - gunicorn
      - socketio

volumes:
  frappe-data:
  frappe-logs:
  frappe-sites:
  mariadb-data:
