x-frappe-image: &frappe_image
    image: frappe/erpnext:latest

x-frappe-service-defaults: &frappe_service_defaults
    volumes:
      - ./wait-for-configurator.sh:/usr/local/bin/wait-for-configurator.sh
      - frappe-data:/home/frappe/frappe-bench
      - frappe-logs:/home/frappe/logs
    working_dir: /home/frappe/frappe-bench

x-frappe-service-depends: &frappe_service_depends
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue

x-wait-for-configurator: &wait_for_configurator
    entrypoint: /usr/local/bin/wait-for-configurator.sh
    restart: always

services:
  mariadb:
    image: mariadb:latest
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql

  redis-cache:
    image: redis:alpine
    restart: always

  redis-queue:
    image: redis:alpine
    restart: always

  configurator:
    <<: *frappe_service_defaults
    image: frappe/bench:latest
    entrypoint:
      - bash
      - -c
    command:
      - >
        if [ ! -f /home/frappe/frappe-bench/.configured ]; then
          sudo chown -R frappe:frappe /home/frappe/frappe-bench &&
          sudo chown -R frappe:frappe /home/frappe/logs &&
          bench init --skip-redis-config-generation --version=${FRAPPE_VERSION} --ignore-exist /home/frappe/frappe-bench &&
          bench set-config -g db_type mariadb &&
          bench set-config -g db_host mariadb &&
          bench set-config -g redis_cache redis://redis-cache:6379 &&
          bench set-config -g redis_queue redis://redis-queue:6379 &&
          bench set-config -g redis_socketio redis://redis-queue:6379 &&
          bench set-config -gp developer_mode 1 &&
          bench new-site --no-mariadb-socket --db-root-password=${DB_ROOT_PASSWORD} --admin-password=${SITE_PASSWORD} --set-default ${SITE_NAME} &&
          bench enable-scheduler &&
          pip install --no-warn-script-location -U -e ./apps/frappe &&
          touch /home/frappe/frappe-bench/.configured
        else
          echo "Configuration already completed."
        fi

  gunicorn:
    <<: [*frappe_image, *frappe_service_defaults, *frappe_service_depends, *wait_for_configurator]
    command: /home/frappe/frappe-bench/env/bin/gunicorn -b 0.0.0.0:8000 -w 4 --max-requests 1200 --max-requests-jitter 50 -t 120 frappe.app:application --preload

  socketio:
    <<: [*frappe_image, *frappe_service_defaults, *frappe_service_depends, *wait_for_configurator]
    command: node apps/frappe/socketio.js

  watch:
    <<: [*frappe_image, *frappe_service_defaults, *frappe_service_depends, *wait_for_configurator]
    command: bench watch

  schedule:
    <<: [*frappe_image, *frappe_service_defaults, *frappe_service_depends, *wait_for_configurator]
    command: bench schedule

  worker_short:
    <<: [*frappe_image, *frappe_service_defaults, *frappe_service_depends, *wait_for_configurator]
    command: bench worker --queue short

  worker_long:
    <<: [*frappe_image, *frappe_service_defaults, *frappe_service_depends, *wait_for_configurator]
    command: bench worker --queue long

  worker_default:
    <<: [*frappe_image, *frappe_service_defaults, *frappe_service_depends, *wait_for_configurator]
    command: bench worker --queue default

  web:
    <<: [*frappe_image, *frappe_service_defaults, *wait_for_configurator]
    command: nginx-entrypoint.sh
    environment:
      BACKEND: gunicorn:8000
      SOCKETIO: socketio:9000
      FRAPPE_SITE_NAME_HEADER: ${SITE_NAME:-$$host}
      UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
      UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
      UPSTREAM_REAL_IP_RECURSIVE: ${UPSTREAM_REAL_IP_RECURSIVE:-off}
      PROXY_READ_TIMEOUT: ${PROXY_READ_TIMEOUT:-120}
      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE:-50m}
    depends_on:
      - gunicorn
      - socketio

volumes:
  frappe-data:
  frappe-logs:
  mariadb-data:
